// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DevicesMacs() {
  return window['go']['main']['App']['DevicesMacs']();
}

export function GetRate() {
  return window['go']['main']['App']['GetRate']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HVOff() {
  return window['go']['main']['App']['HVOff']();
}

export function HVOn() {
  return window['go']['main']['App']['HVOn']();
}

export function PrintT0() {
  return window['go']['main']['App']['PrintT0']();
}

export function ReadData() {
  return window['go']['main']['App']['ReadData']();
}

export function ScanDevices() {
  return window['go']['main']['App']['ScanDevices']();
}

export function StartAcquisition() {
  return window['go']['main']['App']['StartAcquisition']();
}

export function UpdateConfig() {
  return window['go']['main']['App']['UpdateConfig']();
}
