// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNetworkInterfaces():Promise<Array<string>>;

export function HVOff(arg1:number):Promise<void>;

export function HVOn(arg1:number):Promise<void>;

export function LoadConfiguration(arg1:string):Promise<void>;

export function SaveConfiguration(arg1:string):Promise<void>;

export function ScanDevices():Promise<void>;

export function SelectConfigFile():Promise<string>;

export function SetDACThreshold(arg1:number,arg2:number):Promise<void>;

export function SetVCXO(arg1:number,arg2:number):Promise<void>;

export function StartConnection(arg1:string):Promise<boolean>;

export function StartRun():Promise<void>;

export function StopRun():Promise<void>;

export function UpdateCardConfig(arg1:number,arg2:{[key: string]: any},arg3:{[key: string]: any}):Promise<void>;

export function UpdateGlobalConfig(arg1:{[key: number]: {[key: string]: any}},arg2:{[key: number]: {[key: string]: any}}):Promise<void>;
