// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRate():Promise<void>;

export function HVOff():Promise<void>;

export function HVOn():Promise<void>;

export function ReadData():Promise<void>;

export function ScanDevices():Promise<void>;

export function SetDACThr():Promise<void>;

export function SetVCXO():Promise<void>;

export function StartRun():Promise<void>;

export function StopRun():Promise<void>;

export function UpdateCardConfig(arg1:number,arg2:{[key: string]: any},arg3:{[key: string]: any}):Promise<void>;
