// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRate() {
  return window['go']['main']['App']['GetRate']();
}

export function HVOff() {
  return window['go']['main']['App']['HVOff']();
}

export function HVOn() {
  return window['go']['main']['App']['HVOn']();
}

export function LoadConfiguration(arg1) {
  return window['go']['main']['App']['LoadConfiguration'](arg1);
}

export function ReadData() {
  return window['go']['main']['App']['ReadData']();
}

export function SaveConfiguration(arg1) {
  return window['go']['main']['App']['SaveConfiguration'](arg1);
}

export function ScanDevices() {
  return window['go']['main']['App']['ScanDevices']();
}

export function SelectConfigFile() {
  return window['go']['main']['App']['SelectConfigFile']();
}

export function SetDACThr() {
  return window['go']['main']['App']['SetDACThr']();
}

export function SetVCXO() {
  return window['go']['main']['App']['SetVCXO']();
}

export function StartRun() {
  return window['go']['main']['App']['StartRun']();
}

export function StopRun() {
  return window['go']['main']['App']['StopRun']();
}

export function UpdateCardConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCardConfig'](arg1, arg2, arg3);
}

export function UpdateGlobalConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateGlobalConfig'](arg1, arg2);
}
